# -*- coding: utf-8 -*-
"""1 oct KNNC iris practical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqcwbmPcmp4ZXyrB5P_c5mMu2WT0Ev-J
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

from sklearn.datasets import load_iris

iris=load_iris()

iris

iris['data']

iris['target']

iris['feature_names']

dataset = pd.DataFrame(iris['data'],columns=iris['feature_names'])

dataset

dataset['class_label']=iris['target']

dataset

X=dataset.iloc[:,0:4].values

X

y=dataset.iloc[:,4].values

y

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

X_train.shape

X_train

y_train

X_test.shape

from sklearn.neighbors import KNeighborsClassifier

model=KNeighborsClassifier(n_neighbors=3,weights='distance',n_jobs=-1)

model.fit(X_train,y_train)

#eval

y_pred=model.predict(X_test)

y_pred

y_test

from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))









